-- AlterTable
ALTER TABLE "Topic" ADD COLUMN     "classId" INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE "Topic" ADD CONSTRAINT "Topic_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
